---
title: "Data analysis"
author: "Aoyue Bi"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: simplex 
    highlight: haddock 
---

# Pipeline: haplotype heatmap for Nean and Den
## Step1: Generate heatmap file

```{r eval=FALSE, include=FALSE}
library(conflicted)
library(dplyr)
library(readxl)
library(tidyverse)
# Explicitly specify preference for dplyr's select function
conflict_prefer("select", "dplyr")
conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::rename)

### Place target_genes at the top so that subsequent steps don't require modifying target_genes individually, making it much more convenient to run directly.
target_genes <- c("PRDM16")
target_genes <- c("CSGALNACT2")
target_genes <- c("PRKCH")
target_genes <- c("CH25H")
###============================================================================= parameter
popfile <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/007_ASMai/000_popInfo/003_PopInfo_APG_addArchaic.txt"
###============================================================================= parameter loop method to call parameters
dfpara <- readxl::read_xlsx("/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/000_gene_hsmap/gene_block_hsmap.xlsx") %>% 
  filter(Archaic == "Neanderthal") %>% 
  filter(IfRun == "N") %>% 
  distinct(ChunkID,.keep_all = T)

# Read population information file (only needs to be read once)
dfpop <- read_tsv(popfile) %>% select(Assembly_ID, Pop, Anc)
# Define base paths
base_hapmap_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/001_DenOri"
base_output_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene"
###============================================================================= end of parameters

df_target <- dfpara %>% filter(GeneName %in% target_genes)
dfpara0 <- dfpara
for(i in 1:nrow(dfpara0)) {
 # Get parameters for current gene
  geneName <- dfpara0$GeneName[i]
  DenBlock <- str_sub(dfpara0$ChunkID[i],2) 
  archaic <- dfpara0$Archaic[i]
  BlockID <- dfpara0$ChunkID[i]
  
  cat("Processing gene:", geneName, ", block:", DenBlock, "\n")
  
  if(archaic == "Denisovan"){
  # Construct file path
  hapmapfile <- file.path(base_hapmap_path, paste0("Den_", DenBlock, ".merge.easy_region.filt_chr.hapmap.xlsx"))
  # outfile <- file.path(base_output_path, paste0(geneName,"_D",DenBlock, "_forheatmap.txt"))
    
  }
  if(archaic == "Neanderthal"){
  # Construct file path
  hapmapfile <- file.path(base_hapmap_path, paste0("Nean_", DenBlock, ".merge.easy_region.filt_chr.hapmap.xlsx"))
  # outfile <- file.path(base_output_path, paste0(geneName,"_N",DenBlock, "_forheatmap.txt"))

  }
  outfile <- file.path(base_output_path, paste0(geneName,"_",BlockID, "_forheatmap.txt")) 
  
  
  # Check if hapmap file exists
  if(!file.exists(hapmapfile)) {
    cat("File does not exist, skipping:", hapmapfile, "\n")
    next  # Skip current loop, continue to next gene
  }
  
  cat("File exists, starting processing...\n")  
  
df0 <- read_tsv(hapmapfile) %>% 
    rename(Den = `Den-Den`, NeanAltai = `Nean-Altai`, NeanVin = `Nean-Vin`, NeanCha = `Nean-Cha`) %>% 
  arrange(POS)

### Data filtering, step 1: Filter POS based on conditions
df1 <- df0 %>% 
  # filter(str_length(REF) == 1, str_length(ALT) ==1) %>% 
  select(-POS_HG38) %>% 
  pivot_longer(cols = `KOR01-Mat`:last_col(), names_to = "Assembly_ID", values_to = "Geno") %>% 
  left_join(dfpop,by=c("Assembly_ID")) %>% 
  ############# First filtering method: frequency filtering
  ### Filter based on frequency, requiring the frequency of each position across all individuals to be greater than 0.05
  group_by(POS) %>%
  summarise(geno_sum = sum(Geno), n = 2*n(), fre = geno_sum/n) %>%
  filter(0.05 < fre, fre < 0.95 ) %>%
  ungroup() %>%
  select(POS)
  

df2 <- df0 %>% 
  inner_join(df1,by = c("POS"))
  
### Data filtering, step 2: Filter samples
df3 <- df2 %>% 
  pivot_longer(cols = `KOR01-Mat`:last_col(), names_to = "Assembly_ID", values_to = "Geno") %>% 
  left_join(dfpop,by=c("Assembly_ID")) %>% 
  # filter(Anc != "AFR") %>% 
  select(-c(Pop,Anc)) %>% 
  ### Transpose back to the original format
  pivot_wider(names_from = Assembly_ID, values_from = Geno)

### After filtering, prepare the file format required for pheatmap
df4 <- df3 %>% 
   ### Note: Select hg38 coordinates for subsequent annotation additions === Later modification, select chm13 coordinates for adding SV annotation information
  ### Select only one type of archaic
  select(POS,c(NeanAltai,`KOR01-Mat`:last_col())) %>% 
  pivot_longer(
    cols = -POS,  # All columns except POS
    names_to = "Assembly_ID",  # Column names become a new column
    values_to = "Value"   # Values become a new column
  ) %>% 
  pivot_wider(
    names_from = POS,  # Use POS values as new column names
    values_from = Value     # Fill with values from Value column
  )  
  
### Output dataframe
### write_tsv(df4, "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene/001_CSGALNACT2.txt")
write_tsv(df4, outfile)

} ### for loop end



```

## Step2-1: Create introgression site file - manually

Note: This reads information from a manually annotated introgression sites file and outputs the format required for heatmap.

```{r}
target_genes <- c("PRDM16")
target_genes <- c("CSGALNACT2")
target_genes <- c("PRKCH")
target_genes <- c("CH25H")
###============================================================================= parameters
dfpara <- readxl::read_xlsx("/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/000_gene_hsmap/gene_block_hsmap.xlsx") %>% 
  filter(GeneName != "GRM5") %>% 
  filter(Archaic == "Neanderthal")
# Define base paths
base_hapmap_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/002_DenModify"
base_output_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene"

###============================================================================= end of parameters

df_target <- dfpara %>% filter(GeneName %in% target_genes)
dfpara0 <- df_target
for(i in 1:nrow(dfpara0)) {
 # Get parameters for current gene
  geneName <- dfpara0$GeneName[i]
  DenBlock <- str_sub(dfpara0$ChunkID[i], 2) 
  archaic <- dfpara0$Archaic[i]
  
  cat("Processing gene:", geneName, ", block:", DenBlock, "\n")
  
  # Construct file path
  hapmapfile <- file.path(base_hapmap_path, paste0("Nean_", DenBlock, ".merge.easy_region.filt_chr.hapmap.xlsx"))
  outfile <- file.path(base_output_path, paste0(geneName, "_N", DenBlock, "_introgressionSites.txt"))
  
  # Check if hapmap file exists
  if(!file.exists(hapmapfile)) {
    cat("File does not exist, skipping:", hapmapfile, "\n")
    next  # Skip current loop, continue to next gene
  }
  
  cat("File exists, starting processing...\n")  

  df0 <- read_xlsx(hapmapfile, sheet = str_c("N", DenBlock), col_names = FALSE) %>% 
    # Set column names - based on your previously used column names
  rename(
    CHR = ...1,
    POS = ...2,
    REF = ...3,
    ALT = ...4,
    POS_HG38 = ...5,
    Den = ...9,
    NeanAltai = ...8,
    NeanVin = ...6,
    NeanCha = ...7
  ) %>% 
    arrange(POS) %>% 
    ### Add annotation: SNP or SV
    mutate(VariationType = if_else(str_length(REF) > 1 | str_length(ALT) > 1, "Indel", "Introgressed SNP"))
  
  df1 <- df0 %>% select(POS_CHM13 = POS, VariationType)
  
  write_tsv(df1, outfile)
    

}

```




## Step2-2: Create introgression site file - automatically

```{r}

target_genes <- c("PRDM16")
target_genes <- c("CSGALNACT2")
target_genes <- c("PRKCH")
target_genes <- c("CH25H")

###============================================================================= parameters
dfpop <- read_tsv("/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/007_ASMai/000_popInfo/003_PopInfo_APG_addArchaic.txt") %>% select(Assembly_ID, Pop, Anc)

dfpara <- readxl::read_xlsx("/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/000_gene_hsmap/gene_block_hsmap.xlsx") %>% 
  filter(GeneName != "GRM5") %>% 
  # filter(Archaic == "Neanderthal") %>% 
  # filter(IfRun == "N") %>% 
  # distinct(ChunkID, .keep_all = TRUE) %>% 
  mutate(a = 1)

# Define base paths
base_hapmap_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/001_DenOri"
base_output_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene"
base_output_path2 <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/006_hapmapFre"
###============================================================================= end of parameters

df_target <- dfpara %>% 
  filter(GeneName %in% target_genes) %>%
  # filter(ChunkID %in% target_chunks ) %>% 
  mutate(a = 1)

dfpara0 <- df_target
for(i in 1:nrow(dfpara0)) {
 # Get parameters for current gene
  geneName <- dfpara0$GeneName[i]
  DenBlock <- str_sub(dfpara0$ChunkID[i], 2) 
  archaic <- dfpara0$Archaic[i]
  BlockID <- dfpara0$ChunkID[i]
  
  cat("Processing gene:", geneName, ", block:", DenBlock, "\n")
  
  if(archaic == "Denisovan"){
    archaicInhapmap <- "Den"
  # Construct file path
  hapmapfile <- file.path(base_hapmap_path, paste0("Den_", DenBlock, ".merge.easy_region.filt_chr.hapmap.xlsx"))
  }
  if(archaic == "Neanderthal"){
    archaicInhapmap <- "NeanAltai"
  # Construct file path
  hapmapfile <- file.path(base_hapmap_path, paste0("Nean_", DenBlock, ".merge.easy_region.filt_chr.hapmap.xlsx"))
  }
  
  outfile <- file.path(base_output_path, paste0(geneName, "_", BlockID, "_introgressionSites.txt")) 
  outfile2 <- file.path(base_output_path2, paste0(geneName, "_", BlockID, "_AllSitesFrequency.txt")) 
  
  # Construct file path
  # hapmapfile <- file.path(base_hapmap_path, paste0("Nean_", DenBlock, ".merge.easy_region.filt_chr.hapmap.xlsx"))
  # # hapmapfile <- file.path(base_hapmap_path, paste0("Nean_", DenBlock, ".merge.filt_chr.hapmap.xlsx"))
  # outfile <- file.path(base_output_path, paste0(geneName, "_N", DenBlock, "_introgressionSites.txt"))
  
  # Check if hapmap file exists
  if(!file.exists(hapmapfile)) {
    cat("File does not exist, skipping:", hapmapfile, "\n")
    next  # Skip current loop, continue to next gene
  }
  
  ### If introgression sites were manually created, skip automatic creation
  if(file.exists(outfile)) {
    cat("File already exists, skipping:", outfile, "\n")
    next  # Skip current loop, continue to next gene
  }
  
  cat("File exists, starting processing...\n")  

  
  
  ### ============================= Start automatically searching for introgression sites 
  # hapmapfile <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/013_centromere/001_ori/chr5.cent-left-chunk.merge.filt_chr.hapmap.xlsx"
  # 
  # hapmapfile <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/chr5.cent-right-chunk.merge.filt_chr.hapmap.xlsx"
  
df0 <- read_tsv(hapmapfile) %>% 
    rename(Den = `Den-Den`, NeanAltai = `Nean-Altai`, NeanVin = `Nean-Vin`, NeanCha = `Nean-Cha`) %>% 
  arrange(POS) 
  
  ### Data filtering, filter POS based on conditions
df1 <- df0 %>% 
  # filter(str_length(REF) == 1, str_length(ALT) == 1) %>% 
  # select(-POS_HG38) %>% 
  pivot_longer(cols = `KOR01-Mat`:last_col(), names_to = "Assembly_ID", values_to = "Geno") %>% 
  left_join(dfpop, by = c("Assembly_ID")) %>% 
  ### Remove entire samples containing -1 in Assembly_ID
  group_by(Assembly_ID) %>%
  filter(!any(Geno == -1)) %>%
  ungroup() %>% 
  mutate(AncIfAFR = if_else(Anc == "AFR", "AFR", "nonAFR")) %>% 
  ############# First filtering method: frequency filtering
  ### Filter based on frequency, requiring frequency > 0.05 for each position across all individuals
  group_by(`#CHROM`, POS, REF, ALT, POS_HG38, NeanVin, NeanCha, NeanAltai, Den, AncIfAFR) %>%
  summarise(geno_sum = sum(Geno), n = 2*n(), fre = geno_sum/n) %>% ungroup()

### note: geno_sum values are either 0 or 2, so the sum is twice the actual number of individuals. Here n is not the actual number of individuals, but Assembly_ID multiplied by 2. The calculated frequency is geno_sum/2*n(). If frequency is 0.009708738 and 2*n() is 206, then how many individuals does this appear in? 0.009708738*206 = 2, so it appears in 1 individual.
n_AFR <- df1 %>% filter(AncIfAFR == "AFR") %>% select(n) %>% distinct(n) %>% pull
n_nonAFR <- df1 %>% filter(AncIfAFR == "nonAFR") %>% select(n) %>% distinct(n) %>% pull

df2 <- df1 %>% 
  dplyr::select(-geno_sum, -n) %>% 
  pivot_wider(names_from = AncIfAFR, values_from = fre) %>% 
  arrange(-.data[[archaicInhapmap]], AFR, -nonAFR) %>% 
  ### Sites with count greater than or equal to 5 are considered introgression sites
  mutate(IfIntrogression = case_when(
    !!sym(archaicInhapmap) == 2 & AFR == 0 & nonAFR*n_nonAFR/2 > 5 ~ "Introgressed",
    !!sym(archaicInhapmap) == 1 & AFR == 0 & nonAFR*n_nonAFR/2 > 5 ~ "Introgressed",
    !!sym(archaicInhapmap) == 0 & AFR == 1 & (n_nonAFR - nonAFR*n_nonAFR)/2 > 5 ~ "Introgressed",
    TRUE ~ "Nonintrogressed"
  )) %>% 
  ### nAFR_geno2 means number of individuals with genotype 2
  mutate(nAFR_geno2 = AFR*n_AFR/2, nnonAFR_geno2 = nonAFR*n_nonAFR/2) %>% 
  mutate(n_AFR = n_AFR/2, n_nonAFR = n_nonAFR/2)

### Output dataframe
# write_tsv(df2, outfile2)
### Format only specific decimal columns
df2 %>%
  mutate(across(c(AFR, nonAFR), ~ round(., 3))) %>%
  mutate(across(c(nAFR_geno2, nnonAFR_geno2), ~ round(., 0))) %>%
  write_tsv(outfile2)

df3 <- df2 %>% 
  filter(IfIntrogression == "Introgressed") %>% 
    # Set column names - based on your previously used column names
  # rename(CHR = `#CHROM`) %>% 
  arrange(POS) %>% 
    ### Add annotation: SNP or SV
  mutate(VariationType = if_else(str_length(REF) > 1 | str_length(ALT) > 1, "Indel", "Introgressed SNP"))
  
  df4 <- df3 %>% select(POS_CHM13 = POS, VariationType)
  
  # write_tsv(df4, outfile)
}


```



## Step3: Plot pheatmap

```{r}
target_genes <- c("PRDM16")
target_genes <- c("CSGALNACT2")
target_genes <- c("PRKCH")
target_genes <- c("CH25H")

###============================================================================= parameters
popfile <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/007_ASMai/000_popInfo/003_PopInfo_APG_addArchaic.txt"
# heatmapfile <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene/CH25H_forheatmap.txt"
# introSitesfile <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene/CH25H_introgressionSites.txt"

###============================================================================= parameters
dfpara <- readxl::read_xlsx("/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/000_gene_hsmap/gene_block_hsmap.xlsx") %>% 
  filter(GeneName != "GRM5") %>% 
  # filter(Archaic == "Neanderthal") %>% 
  # filter(IfRun == "N") %>% 
  distinct(ChunkID, .keep_all = TRUE)

# Define base paths
base_introSites_path <- "/Users/Aoyue/project_pos/APG_archaicDNA/002_dataAnalysis/011_adaptiveIntrogression/005_geneHaplotype/001_gene"

###============================================================================= end of parameters
# Create or open log file before starting the loop
log_file <- "pheatmap_errors.log"

df_target <- dfpara %>% filter(GeneName %in% target_genes)
dfpara0 <- df_target

for(i in 1:nrow(dfpara0)) {
 # Get parameters for current gene
  geneName <- dfpara0$GeneName[i]
  DenBlock <- str_sub(dfpara0$ChunkID[i], 2) 
  archaic <- dfpara0$Archaic[i]
  
  cat("Processing gene:", geneName, ", block:", DenBlock, "\n")
  
  # Construct file paths
  # heatmapfile <- file.path(base_introSites_path, paste0(geneName, "_D", DenBlock, "_forheatmap.txt"))
  # introSitesfile <- file.path(base_introSites_path, paste0(geneName, "_D", DenBlock, "_introgressionSites.txt"))
  
  heatmapfile <- file.path(base_introSites_path, paste0(geneName, "_N", DenBlock, "_forheatmap.txt"))
  introSitesfile <- file.path(base_introSites_path, paste0(geneName, "_N", DenBlock, "_introgressionSites.txt"))
  
  # Check if hapmap file exists
  if(!file.exists(heatmapfile)) {
    cat("File does not exist, skipping:", heatmapfile, "\n")
    next  # Skip current loop, continue to next gene
  }
  
  cat("File exists, starting processing...\n")  

############################################################## File preparation
df_group <- read_tsv(popfile) %>% select(Assembly_ID, Pop, Anc)
df_gene <- read_tsv(heatmapfile)
population_order <- c("Archaic", "EAS", "SEA", "SAS", "EUR", "AMR", "AFR")

###### Perform statistics on the file
df_filterPos0 <- df_gene %>% 
  pivot_longer(cols = c(2:last_col()), names_to = "POS_CHM13", values_to = "Geno")
  ### Filter positions
  # filter(POS_CHM13 >= Start_heatmap, POS_CHM13 <= End_heatmap) 

df_filterPos <-  df_filterPos0 %>% 
  pivot_wider(names_from = POS_CHM13, values_from = Geno)

### Some statistical information
final_hapmapRange <- df_filterPos0 %>%
  summarise(
    min_pos = min(as.numeric(POS_CHM13)),
    max_pos = max(as.numeric(POS_CHM13)),
    hapmap_length = (max_pos - min_pos)/1000,
    n_variants = length(unique(POS_CHM13))  
  )

###### 
# Merge genotype file and grouping file for categorization
df_gene2 <- df_gene %>% 
  left_join(df_group, by = c("Assembly_ID")) %>% 
  relocate(Pop, Anc, .after = Assembly_ID) %>% 
  mutate(Anc = factor(Anc, levels = population_order)) %>%
  arrange(Anc)  

############################################################## Sorting
# Group by Population column and sort by all numeric columns after Population
df_gene_sorted <- df_gene2 %>%
  group_by(Anc) %>%
  arrange(across(where(is.numeric)), .by_group = TRUE) %>%
  ungroup()

# View results
head(df_gene_sorted)
df <- df_gene_sorted

############################################################## Final file preparation
### Plotting file
df_1 <- df %>% 
  select(-Anc, -Pop) %>% 
  column_to_rownames("Assembly_ID")

###### Debug section
# Check if dataframe has NA values
if (any(is.na(df_1))) {
  warning("Dataframe df_1 contains NA values, skipping current loop")
  error_msg <- paste(Sys.time(), "| Gene:", geneName, "| Block:", DenBlock, "| Reason: Contains NA values\n")
  cat("Found NA values, skipping pheatmap\n")
  # Write to log file
  write(error_msg, file = log_file, append = TRUE)
  next  # Skip current loop, continue to next gene
}

### Annotation file
df_2 <- df %>%
  select(Assembly_ID, Anc, Pop) %>%
  select(-Pop) %>% 
  mutate(IfArchaic = if_else(Assembly_ID == "NeanAltai", "Archaic", NA)) %>% 
  relocate(IfArchaic, .before = Anc) %>% 
  column_to_rownames("Assembly_ID")

### Column annotation file
df_3 <- df %>% 
  select(-Anc, -Pop) %>% 
  column_to_rownames("Assembly_ID") 
  # t() %>% 
  # as.data.frame()
  ###### Get column names
  
  # Check if hapmap file exists
  if(file.exists(introSitesfile)) {
    cat("File exists, executing:", introSitesfile, "\n")
    # next  # Skip current loop, continue to next gene
    
dfintro <- read_tsv(introSitesfile)
# Get column names and create dataframe
df_colAnno <- tibble(POS_CHM13 = as.numeric(colnames(df_3))) %>% 
  inner_join(dfintro, by = c("POS_CHM13")) %>% 
  column_to_rownames("POS_CHM13")
  
### Count number of introgressed variants
final_hapmapRange$n_introgressed_variants <- nrow(df_colAnno)
write_tsv(final_hapmapRange, file.path(base_introSites_path, paste0(geneName, "_N", DenBlock, "_finalStatistic.txt")))
############################################################## Start plotting
### Custom annotation colors list
library(RColorBrewer)
### Color assignment
ann_colors <-  list(Anc = c("Archaic" = "cyan", 
                                 "EAS" = "#FF7F00",
                                "SEA" = "#E41A1C",
                                 "SAS" = "#984EA3",
                                 "EUR" = "#4DAF4A",
                                 "AMR" = "#FFB347",
                          "AFR" = "#7B241C"
                                 ),
                    IfArchaic = c("Archaic" = "cyan"),
                    VariationType = c(`Introgressed SNP` = "red", "Indel" = "blue"))

## 

colors <- brewer.pal(9, "YlGnBu")[c(1, 4, 7)]
# colB <- colorRampPalette(c("lightyellow", "skyblue", "indianred"))(100)
colB <- c("#F2F1F1", "black")

library(pheatmap)
# conflicted::conflicts_prefer(pheatmap::pheatmap)
### First draw a plot without any modifications
# p <- pheatmap(df_1,
#               cluster_rows = TRUE,
#               cluster_cols = FALSE,
#               border_color = NA,
#               show_colnames = FALSE,
#               show_rownames = FALSE,
#               # filename = "~/Documents/heatmap_ori.pdf",
#               filename = str_c("~/Documents/heatmap_", geneName, "_D", DenBlock, "_ori.pdf"),
#               width = 8, height = 10,
#               main = str_c(geneName, "-", archaic))

### Further beautify
p <- pheatmap::pheatmap(df_1, 
              display_numbers = FALSE,
              cluster_rows = TRUE,
              cluster_cols = FALSE,
              # treeheight_row = 0, ## Cluster but don't display tree structure
              # treeheight_col = 0, ## Cluster but don't display tree structure
              show_colnames = FALSE, ## Don't show column names
              show_rownames = FALSE, ## Don't show row names
              # angle_col = 90, ### Set column name tilt
              color = colB,
              # breaks = breaks,
              cutree_rows = 2,  # Divide rows into 2 groups
              legend = TRUE, ### Show heatmap legend
              annotation_row = df_2, ## Annotation dataframe
              annotation_col = df_colAnno,
              annotation_names_row = FALSE,
              annotation_names_col = FALSE,
              annotation_legend = TRUE,
              annotation_colors = ann_colors, ## Corresponding colors for annotation dataframe factors
              fontsize_row = 7, # Set row name font size (can be adjusted as needed)
              fontsize_col = 7,
              fontsize = 9,
              border_color = NA,
              # filename = "~/Documents/heatmap1.pdf",
              # filename = str_c("~/Documents/heatmap1_", geneName, "_D", DenBlock, ".pdf"),
              filename = str_c("~/Documents/heatmap1_", geneName, "_N", DenBlock,
                               "_", final_hapmapRange$hapmap_length, "kb",
                               "_", final_hapmapRange$n_variants, "variants",
                               "_", final_hapmapRange$n_introgressed_variants, "introgressedVariants",
                               ".pdf"),              
              width = 6.5, height = 6,
              main = str_c(geneName, "-", archaic)
         )

p

### Get clustered row names and manually check
### p$tree_row[["order"]]: This part gets an element named order, assuming it's a vector containing row order or indices
rowdata = rownames(df_1[p$tree_row[["order"]], ])
write.table(rowdata, file = str_c("/Users/Aoyue/Documents/", geneName, "_N", DenBlock, "_treeOrder.txt"), row.names = FALSE, col.names = FALSE, quote = FALSE)
    
  } else {
    
  # dfintro <- read_tsv(introSitesfile)
# Get column names and create dataframe
# df_colAnno <- tibble(POS_CHM13 = as.numeric(colnames(df_3))) %>% 
#   inner_join(dfintro, by = c("POS_CHM13")) %>% 
#   column_to_rownames("POS_CHM13")
  
### Count number of introgressed variants
# final_hapmapRange$n_introgressed_variants <- nrow(df_colAnno)
write_tsv(final_hapmapRange, file.path(base_introSites_path, paste0(geneName, "_N", DenBlock, "_finalStatistic_simple.txt")))
############################################################## Start plotting
### Custom annotation colors list
library(RColorBrewer)
### Color assignment
ann_colors <-  list(Anc = c("Archaic" = "cyan", 
                                 "EAS" = "#FF7F00",
                                "SEA" = "#E41A1C",
                                 "SAS" = "#984EA3",
                                 "EUR" = "#4DAF4A",
                                 "AMR" = "#FFB347",
                          "AFR" = "#7B241C"
                                 ),
                    IfArchaic = c("Archaic" = "cyan")
                    # VariationType = c(`Introgressed SNP` = "red", "Indel" = "blue")
                    )

## 

colors <- brewer.pal(9, "YlGnBu")[c(1, 4, 7)]
# colB <- colorRampPalette(c("lightyellow", "skyblue", "indianred"))(100)
colB <- c("#F2F1F1", "black")

library(pheatmap)
p <- pheatmap::pheatmap(df_1, 
              display_numbers = FALSE,
              cluster_rows = TRUE,
              cluster_cols = FALSE,
              # treeheight_row = 0, ## Cluster but don't display tree structure
              # treeheight_col = 0, ## Cluster but don't display tree structure
              show_colnames = FALSE, ## Don't show column names
              show_rownames = FALSE, ## Don't show row names
              # angle_col = 90, ### Set column name tilt
              color = colB,
              # breaks = breaks,
              cutree_rows = 2,  # Divide rows into 2 groups
              legend = TRUE, ### Show heatmap legend
              annotation_row = df_2, ## Annotation dataframe
              # annotation_col = df_colAnno,
              annotation_names_row = FALSE,
              annotation_names_col = FALSE,
              annotation_legend = TRUE,
              annotation_colors = ann_colors, ## Corresponding colors for annotation dataframe factors
              fontsize_row = 7, # Set row name font size (can be adjusted as needed)
              fontsize_col = 7,
              fontsize = 9,
              border_color = NA,
              # filename = "~/Documents/heatmap1.pdf",
              # filename = str_c("~/Documents/heatmap1_", geneName, "_D", DenBlock, ".pdf"),
              filename = str_c("~/Documents/heatmap1_", geneName, "_N", DenBlock,
                               "_", final_hapmapRange$hapmap_length, "kb",
                               "_", final_hapmapRange$n_variants, "variants",
                               "_", final_hapmapRange$n_introgressed_variants, "introgressedVariants",
                               ".pdf"), width = 6.5, height = 6,
              main = str_c(geneName, "-", archaic)
         )

p

### Get clustered row names and manually check
### p$tree_row[["order"]]: This part gets an element named order, assuming it's a vector containing row order or indices
rowdata = rownames(df_1[p$tree_row[["order"]], ])
write.table(rowdata, file = str_c("/Users/Aoyue/Documents/", geneName, "_N", DenBlock, "_treeOrder.txt"), row.names = FALSE, col.names = FALSE, quote = FALSE)
    
  } ### End of introgression sites loop

} ### End of for loop

```


